# Using describe() on a DataFrame
# Here we will see how the describe() method generates a statistical summary for numeric columns such as age and salary. This is a basic use case of describe() to give us an overview of key statistical metrics across the dataset.
import pandas as pd

data = pd.read_csv(r"D:\Basic-Python\Day3\nba.csv")
print("NBA Dataset:")
print(data.head())
print("\nSummary Table Generated by .describe() Method:")
print(data.describe())